// <auto-generated />
using System;
using API_Agenda.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Agenda.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250311182702_UsuarioM")]
    partial class UsuarioM
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Agenda.Shared.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Favorito")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ListaNegra")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Correo = "juan.perez@example.com",
                            Favorito = false,
                            FechaRegistro = new DateTime(2025, 3, 11, 11, 27, 2, 574, DateTimeKind.Local).AddTicks(8575),
                            ListaNegra = true,
                            Nombre = "Juan Pérez",
                            Telefono = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            Correo = "maria.garcia@example.com",
                            Favorito = false,
                            FechaRegistro = new DateTime(2025, 3, 11, 11, 27, 2, 574, DateTimeKind.Local).AddTicks(8660),
                            ListaNegra = false,
                            Nombre = "María García",
                            Telefono = "0987654321"
                        },
                        new
                        {
                            Id = 3,
                            Correo = "carlos.lopez@example.com",
                            Favorito = false,
                            FechaRegistro = new DateTime(2025, 3, 11, 11, 27, 2, 574, DateTimeKind.Local).AddTicks(8664),
                            ListaNegra = true,
                            Nombre = "Carlos López",
                            Telefono = "5555555555"
                        },
                        new
                        {
                            Id = 4,
                            Correo = "ana.martinez@example.com",
                            Favorito = false,
                            FechaRegistro = new DateTime(2025, 3, 11, 11, 27, 2, 574, DateTimeKind.Local).AddTicks(8679),
                            ListaNegra = false,
                            Nombre = "Ana Martínez",
                            Telefono = "1111111111"
                        },
                        new
                        {
                            Id = 5,
                            Correo = "luis.rodriguez@example.com",
                            Favorito = false,
                            FechaRegistro = new DateTime(2025, 3, 11, 11, 27, 2, 574, DateTimeKind.Local).AddTicks(8683),
                            ListaNegra = false,
                            Nombre = "Luis Rodríguez",
                            Telefono = "2222222222"
                        },
                        new
                        {
                            Id = 6,
                            Correo = "sofia.hernandez@example.com",
                            Favorito = false,
                            FechaRegistro = new DateTime(2025, 3, 11, 11, 27, 2, 574, DateTimeKind.Local).AddTicks(8686),
                            ListaNegra = true,
                            Nombre = "Sofía Hernández",
                            Telefono = "3333333333"
                        },
                        new
                        {
                            Id = 7,
                            Correo = "pedro.diaz@example.com",
                            Favorito = false,
                            FechaRegistro = new DateTime(2025, 3, 11, 11, 27, 2, 574, DateTimeKind.Local).AddTicks(8689),
                            ListaNegra = true,
                            Nombre = "Pedro Díaz",
                            Telefono = "4444444444"
                        },
                        new
                        {
                            Id = 8,
                            Correo = "lucia.sanchez@example.com",
                            Favorito = true,
                            FechaRegistro = new DateTime(2025, 3, 11, 11, 27, 2, 574, DateTimeKind.Local).AddTicks(8695),
                            ListaNegra = false,
                            Nombre = "Lucía Sánchez",
                            Telefono = "6666666666"
                        },
                        new
                        {
                            Id = 9,
                            Correo = "jorge.ramirez@example.com",
                            Favorito = false,
                            FechaRegistro = new DateTime(2025, 3, 11, 11, 27, 2, 574, DateTimeKind.Local).AddTicks(8698),
                            ListaNegra = true,
                            Nombre = "Jorge Ramírez",
                            Telefono = "7777777777"
                        },
                        new
                        {
                            Id = 10,
                            Correo = "elena.torres@example.com",
                            Favorito = false,
                            FechaRegistro = new DateTime(2025, 3, 11, 11, 27, 2, 574, DateTimeKind.Local).AddTicks(8701),
                            ListaNegra = true,
                            Nombre = "Elena Torres",
                            Telefono = "8888888888"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
