// <auto-generated />
using System;
using API_Agenda.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Agenda.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Agenda.Shared.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Correo = "juan.perez@example.com",
                            FechaRegistro = new DateTime(2025, 3, 11, 10, 35, 14, 710, DateTimeKind.Local).AddTicks(1252),
                            Nombre = "Juan Pérez",
                            Telefono = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            Correo = "maria.garcia@example.com",
                            FechaRegistro = new DateTime(2025, 3, 11, 10, 35, 14, 710, DateTimeKind.Local).AddTicks(1255),
                            Nombre = "María García",
                            Telefono = "0987654321"
                        },
                        new
                        {
                            Id = 3,
                            Correo = "carlos.lopez@example.com",
                            FechaRegistro = new DateTime(2025, 3, 11, 10, 35, 14, 710, DateTimeKind.Local).AddTicks(1257),
                            Nombre = "Carlos López",
                            Telefono = "5555555555"
                        },
                        new
                        {
                            Id = 4,
                            Correo = "ana.martinez@example.com",
                            FechaRegistro = new DateTime(2025, 3, 11, 10, 35, 14, 710, DateTimeKind.Local).AddTicks(1259),
                            Nombre = "Ana Martínez",
                            Telefono = "1111111111"
                        },
                        new
                        {
                            Id = 5,
                            Correo = "luis.rodriguez@example.com",
                            FechaRegistro = new DateTime(2025, 3, 11, 10, 35, 14, 710, DateTimeKind.Local).AddTicks(1261),
                            Nombre = "Luis Rodríguez",
                            Telefono = "2222222222"
                        },
                        new
                        {
                            Id = 6,
                            Correo = "sofia.hernandez@example.com",
                            FechaRegistro = new DateTime(2025, 3, 11, 10, 35, 14, 710, DateTimeKind.Local).AddTicks(1262),
                            Nombre = "Sofía Hernández",
                            Telefono = "3333333333"
                        },
                        new
                        {
                            Id = 7,
                            Correo = "pedro.diaz@example.com",
                            FechaRegistro = new DateTime(2025, 3, 11, 10, 35, 14, 710, DateTimeKind.Local).AddTicks(1264),
                            Nombre = "Pedro Díaz",
                            Telefono = "4444444444"
                        },
                        new
                        {
                            Id = 8,
                            Correo = "lucia.sanchez@example.com",
                            FechaRegistro = new DateTime(2025, 3, 11, 10, 35, 14, 710, DateTimeKind.Local).AddTicks(1266),
                            Nombre = "Lucía Sánchez",
                            Telefono = "6666666666"
                        },
                        new
                        {
                            Id = 9,
                            Correo = "jorge.ramirez@example.com",
                            FechaRegistro = new DateTime(2025, 3, 11, 10, 35, 14, 710, DateTimeKind.Local).AddTicks(1268),
                            Nombre = "Jorge Ramírez",
                            Telefono = "7777777777"
                        },
                        new
                        {
                            Id = 10,
                            Correo = "elena.torres@example.com",
                            FechaRegistro = new DateTime(2025, 3, 11, 10, 35, 14, 710, DateTimeKind.Local).AddTicks(1269),
                            Nombre = "Elena Torres",
                            Telefono = "8888888888"
                        },
                        new
                        {
                            Id = 11,
                            Correo = "gabriel.fernandez@example.com",
                            FechaRegistro = new DateTime(2025, 3, 11, 10, 35, 14, 710, DateTimeKind.Local).AddTicks(1271),
                            Nombre = "Gabriel Fernández",
                            Telefono = "9999999999"
                        },
                        new
                        {
                            Id = 12,
                            Correo = "natalia.ortega@example.com",
                            FechaRegistro = new DateTime(2025, 3, 11, 10, 35, 14, 710, DateTimeKind.Local).AddTicks(1273),
                            Nombre = "Natalia Ortega",
                            Telefono = "1010101010"
                        },
                        new
                        {
                            Id = 13,
                            Correo = "fernando.ruiz@example.com",
                            FechaRegistro = new DateTime(2025, 3, 11, 10, 35, 14, 710, DateTimeKind.Local).AddTicks(1274),
                            Nombre = "Fernando Ruiz",
                            Telefono = "1212121212"
                        },
                        new
                        {
                            Id = 14,
                            Correo = "paula.castro@example.com",
                            FechaRegistro = new DateTime(2025, 3, 11, 10, 35, 14, 710, DateTimeKind.Local).AddTicks(1276),
                            Nombre = "Paula Castro",
                            Telefono = "1313131313"
                        },
                        new
                        {
                            Id = 15,
                            Correo = "raul.mendoza@example.com",
                            FechaRegistro = new DateTime(2025, 3, 11, 10, 35, 14, 710, DateTimeKind.Local).AddTicks(1278),
                            Nombre = "Raúl Mendoza",
                            Telefono = "1414141414"
                        },
                        new
                        {
                            Id = 16,
                            Correo = "andrea.vega@example.com",
                            FechaRegistro = new DateTime(2025, 3, 11, 10, 35, 14, 710, DateTimeKind.Local).AddTicks(1280),
                            Nombre = "Andrea Vega",
                            Telefono = "1515151515"
                        },
                        new
                        {
                            Id = 17,
                            Correo = "santiago.guzman@example.com",
                            FechaRegistro = new DateTime(2025, 3, 11, 10, 35, 14, 710, DateTimeKind.Local).AddTicks(1281),
                            Nombre = "Santiago Guzmán",
                            Telefono = "1616161616"
                        },
                        new
                        {
                            Id = 18,
                            Correo = "valeria.navarro@example.com",
                            FechaRegistro = new DateTime(2025, 3, 11, 10, 35, 14, 710, DateTimeKind.Local).AddTicks(1283),
                            Nombre = "Valeria Navarro",
                            Telefono = "1717171717"
                        },
                        new
                        {
                            Id = 19,
                            Correo = "ricardo.soto@example.com",
                            FechaRegistro = new DateTime(2025, 3, 11, 10, 35, 14, 710, DateTimeKind.Local).AddTicks(1285),
                            Nombre = "Ricardo Soto",
                            Telefono = "1818181818"
                        },
                        new
                        {
                            Id = 20,
                            Correo = "isabel.romero@example.com",
                            FechaRegistro = new DateTime(2025, 3, 11, 10, 35, 14, 710, DateTimeKind.Local).AddTicks(1286),
                            Nombre = "Isabel Romero",
                            Telefono = "1919191919"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
